### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by MiliusCZ** [werein/react#29]
Please add support for Windows users as well by implementing [cross-env](https://www.npmjs.com/package/cross-env). 

Thank you :)

**Comment by jirikolarik** [comment]
Hey @MiliusCZ, I'm trying to keep this repo as minimal as possible, not sure if adding another dependency which is gonna be used only by 1% of people using this make sense.

You can always modify your packages.json, there will be no changes on `test`, or `build` commands in near feature.
