### ISSUE TITLE
After the project build, run index.html to display the blank interface.

### ISSUE THREAD

**Issue by shiran1992** [werein/react#54]
After the project build, run index.html to display the blank interface.
![default](https://user-images.githubusercontent.com/16955920/33005173-ad225f42-cdff-11e7-95c2-e8eae3c98c16.png)

**Comment by jirikolarik** [comment]
How do you run it? You need to star dev server with `npm start` in project directory

**Comment by shiran1992** [comment]
I see what you mean, that's fine. But I've developed it on this framework, and now I need to build a package, which is the dist folder.In this folder(dist),I ran index.html, which shows the blank, which is what I've just done.    -------Thank you very much for your reply! (from a Chinese guy who is working overtime)

**Comment by jirikolarik** [comment]
You need to run a server, which will server index.html and assets, what you can do with running `npm run server` or `node server` or with php for example, in this case you have to run `php -S localhost:8080` in dist folder.

**Comment by jirikolarik** [comment]
You can also deploy this code to `surge` for example and they will do this for you

**Comment by shiran1992** [comment]
Thank you for your reply .I did what you said, and if you use your empty project, no problem. However, after I have developed on your foundation, the build comes out wrong. 
![default](https://user-images.githubusercontent.com/16955920/33053727-140f6cc6-ceb0-11e7-8760-094005860e89.png)
My package.json
![default](https://user-images.githubusercontent.com/16955920/33053790-6bcb82c4-ceb0-11e7-8919-3a3ab1daa85d.png)

**Comment by shiran1992** [comment]
.babelrc
![default](https://user-images.githubusercontent.com/16955920/33060553-95d76f42-ced3-11e7-9468-5602d41377a7.png)
I think my question should be here. What do you think?

**Comment by jirikolarik** [comment]
Try to move `transform-runtime` and `transform-decorators-legacy` out of development plugins to just `plugins` like here:

<img width="433" alt="screen shot 2017-11-21 at 09 18 26" src="https://user-images.githubusercontent.com/3116918/33061599-01370b12-ce9d-11e7-88f5-4c3722b1fb06.png">

I think this may be it. Because `transform-runtime` is needed while building the project and that is happening in production env (you can see in `packages.json`: `"build": "NODE_ENV=production webpack --config ./webpack.production.js --profile --colors"`). Give it a shot and let me know if it helped

**Comment by shiran1992** [comment]
Now I can look at the interface, but the style is not normal .
![default](https://user-images.githubusercontent.com/16955920/33064253-06c886d0-cee0-11e7-9ed8-5e8f9ac126ae.png)

**Comment by jirikolarik** [comment]
If you wrote API in server.js, you have to run it as well. It is preconfigured to also serve builded project, so if you run `npm run server` both of them - api and react app should work, `php -S localhost:8080` is not an option in this case

**Comment by jirikolarik** [comment]
Did it worked? @shiran1992

**Comment by shiran1992** [comment]
I'm very sorry. I have been busy lately. I didn't pay attention to git news. Then you offered the solution, I tried it, the style was problematic, and then I didn't find the solution. Over the weekend, I used the scaffolding create-react-app provided by facebook's official website to move the previously written functional code, which is now running smoothly.

**Comment by shiran1992** [comment]
I just found out that there is a problem that after the migration, the CSS properties that were used to limit the number of content rows in <p> are not working, so please help me to check it. It was this before, and it worked. 
![default](https://user-images.githubusercontent.com/16955920/33377099-27609dc6-d54b-11e7-955f-a8db30b7e6d4.png)

**Comment by shiran1992** [comment]
JetBrains, I adore this company. Are you near here?

**Comment by jirikolarik** [comment]
I'm glad it worked out for you. Switching to another build setup shouldn't have any effect how css works. If you have some css preprocessors which modifies them, then it might, but I don't believe so. Check compiled css in you browser. Yeah, they're just next door :)
